// @generated
// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AdminAck {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AdminConnection {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="3")]
    pub tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag="4")]
    pub deployment_kind: ::prost::alloc::string::String,
    #[prost(int64, tag="5")]
    pub created_at: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AdminListConnectionsRequest {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AdminListConnectionsResponse {
    #[prost(message, repeated, tag="1")]
    pub connections: ::prost::alloc::vec::Vec<AdminConnection>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateConnectionRequest {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub deployment_kind: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="3")]
    pub tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// sealed server-side; never returned
    #[prost(string, tag="4")]
    pub uri: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateConnectionResponse {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteConnectionRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TestConnectionRequest {
    #[prost(string, tag="1")]
    pub uri: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TestConnectionResponse {
    #[prost(bool, tag="1")]
    pub ok: bool,
    #[prost(string, tag="2")]
    pub error: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AdminUser {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub kind: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="4")]
    pub roles: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag="5")]
    pub status: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListUsersRequest {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListUsersResponse {
    #[prost(message, repeated, tag="1")]
    pub users: ::prost::alloc::vec::Vec<AdminUser>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateUserRequest {
    #[prost(string, tag="1")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub password: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="3")]
    pub roles: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateUserResponse {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SetUserRolesRequest {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="2")]
    pub roles: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AuditEvent {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(int64, tag="2")]
    pub ts: i64,
    #[prost(string, tag="3")]
    pub actor: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub op: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub db: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub coll: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub summary: ::prost::alloc::string::String,
    #[prost(int64, tag="9")]
    pub doc_count: i64,
    #[prost(int64, tag="10")]
    pub duration_ms: i64,
    #[prost(string, tag="11")]
    pub status: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListAuditEventsRequest {
    #[prost(int64, tag="1")]
    pub limit: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListAuditEventsResponse {
    #[prost(message, repeated, tag="1")]
    pub events: ::prost::alloc::vec::Vec<AuditEvent>,
}
/// A grant binds a principal to one connection. principal_type is
/// "role", "user", or "group"; principal_id is a role name, user id, or
/// IdP group name.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConnectionGrant {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub principal_type: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub principal_id: ::prost::alloc::string::String,
    #[prost(int64, tag="4")]
    pub created_at: i64,
}
/// connection_id filters to one connection; empty lists every grant in the tenant.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListGrantsRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListGrantsResponse {
    #[prost(message, repeated, tag="1")]
    pub grants: ::prost::alloc::vec::Vec<ConnectionGrant>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GrantConnectionRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub principal_type: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub principal_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevokeConnectionRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub principal_type: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub principal_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginRequest {
    /// tenant slug
    #[prost(string, tag="1")]
    pub tenant: ::prost::alloc::string::String,
    #[prost(oneof="login_request::Login", tags="2, 3")]
    pub login: ::core::option::Option<login_request::Login>,
}
/// Nested message and enum types in `LoginRequest`.
pub mod login_request {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Login {
        #[prost(message, tag="2")]
        Oidc(super::OidcCode),
        #[prost(message, tag="3")]
        Local(super::LocalCreds),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OidcCode {
    #[prost(string, tag="1")]
    pub code: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub redirect_uri: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub code_verifier: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LocalCreds {
    #[prost(string, tag="1")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub password: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginResponse {
    /// JWT
    #[prost(string, tag="1")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub refresh_token: ::prost::alloc::string::String,
    /// unix seconds
    #[prost(int64, tag="3")]
    pub expires_at: i64,
    #[prost(message, optional, tag="4")]
    pub principal: ::core::option::Option<Principal>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RefreshRequest {
    #[prost(string, tag="1")]
    pub refresh_token: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LogoutRequest {
    #[prost(string, tag="1")]
    pub refresh_token: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LogoutResponse {
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WhoAmIRequest {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WhoAmIResponse {
    #[prost(message, optional, tag="1")]
    pub principal: ::core::option::Option<Principal>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Principal {
    #[prost(string, tag="1")]
    pub tenant: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="4")]
    pub roles: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetCapabilitiesRequest {
    /// Connections to report op classes for. Empty returns server-wide
    /// information only. At most 200 per call.
    #[prost(string, repeated, tag="1")]
    pub connection_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetCapabilitiesResponse {
    #[prost(string, tag="1")]
    pub server_version: ::prost::alloc::string::String,
    /// Every mounted RPC as "/package.Service/Method", sorted. A procedure being
    /// listed is the contract that the server serves it.
    #[prost(string, repeated, tag="2")]
    pub procedures: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Behaviour flags within procedures, sorted. An absent flag means the
    /// behaviour is unsupported.
    #[prost(string, repeated, tag="3")]
    pub features: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag="4")]
    pub principal: ::core::option::Option<Principal>,
    /// One entry per requested connection id, in request order.
    #[prost(message, repeated, tag="5")]
    pub connections: ::prost::alloc::vec::Vec<ConnectionCapabilities>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConnectionCapabilities {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    /// A subset of "read", "write", "ddl" and "admin". Empty when the caller
    /// cannot reach the connection, which includes ids that do not exist, so the
    /// response never reveals whether an ungranted connection exists.
    #[prost(string, repeated, tag="2")]
    pub op_classes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// Typed error detail attached to connect errors (mirrors desktop UX).
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MqlErrorDetail {
    /// e.g. "unauthorized", "not_found", "mongo_error"
    #[prost(string, tag="1")]
    pub code: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub message: ::prost::alloc::string::String,
    /// 0 if not a mongo error
    #[prost(int32, tag="3")]
    pub mongo_code: i32,
    #[prost(bool, tag="4")]
    pub retryable: bool,
}
/// References ONLY — never any URI or credential.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConnectionRef {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="3")]
    pub tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// "standalone" | "replica_set" | "sharded" | "atlas"
    #[prost(string, tag="4")]
    pub deployment_kind: ::prost::alloc::string::String,
    /// Op classes the caller may perform here: a subset of "read", "write",
    /// "ddl" and "admin".
    #[prost(string, repeated, tag="5")]
    pub op_classes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListConnectionsRequest {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListConnectionsResponse {
    #[prost(message, repeated, tag="1")]
    pub connections: ::prost::alloc::vec::Vec<ConnectionRef>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetConnectionRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AggregateRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub database: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub collection: ::prost::alloc::string::String,
    /// Extended JSON array of stages
    #[prost(string, tag="4")]
    pub pipeline_json: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExplainRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub database: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub collection: ::prost::alloc::string::String,
    /// "find" | "aggregate"
    #[prost(string, tag="4")]
    pub kind: ::prost::alloc::string::String,
    /// filter (find) or pipeline array (aggregate)
    #[prost(string, tag="5")]
    pub query_json: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExplainResponse {
    /// canonical Extended JSON
    #[prost(string, tag="1")]
    pub plan_json: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FindRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub database: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub collection: ::prost::alloc::string::String,
    /// Extended JSON
    #[prost(string, tag="4")]
    pub filter_json: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub sort_json: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub projection_json: ::prost::alloc::string::String,
    #[prost(int64, tag="7")]
    pub skip: i64,
    #[prost(int64, tag="8")]
    pub limit: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FindBatch {
    /// canonical Extended JSON
    #[prost(string, repeated, tag="1")]
    pub documents_ejson: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CountRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub database: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub collection: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub filter_json: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CountResponse {
    #[prost(int64, tag="1")]
    pub count: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DdlAck {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetCollectionOptionsRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub database: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub collection: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CollectionValidation {
    /// relaxed Extended JSON, "{}" when no validator is set
    #[prost(string, tag="1")]
    pub validator: ::prost::alloc::string::String,
    /// "off" | "moderate" | "strict" | "" when unset
    #[prost(string, tag="2")]
    pub validation_level: ::prost::alloc::string::String,
    /// "error" | "warn" | "" when unset
    #[prost(string, tag="3")]
    pub validation_action: ::prost::alloc::string::String,
}
/// validator is Extended JSON, so a value written by GetCollectionOptions can be
/// sent straight back. An empty validator clears validation. An empty level or
/// action leaves that setting unchanged.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SetValidatorRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub database: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub collection: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub validator: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub validation_level: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub validation_action: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateCollectionRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub database: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub collection: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DropCollectionRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub database: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub collection: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RenameCollectionRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub database: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub collection: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub new_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateViewRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub database: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub view: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub view_on: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub pipeline_json: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DropDatabaseRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub database: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RenameDatabaseRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub database: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub new_name: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeploymentUserAck {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RoleSpec {
    #[prost(string, tag="1")]
    pub role: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub db: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeploymentUser {
    #[prost(string, tag="1")]
    pub user: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub db: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="3")]
    pub roles: ::prost::alloc::vec::Vec<RoleSpec>,
    #[prost(string, repeated, tag="4")]
    pub mechanisms: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListDeploymentUsersRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    /// empty lists users across all databases
    #[prost(string, tag="2")]
    pub database: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListDeploymentUsersResponse {
    #[prost(message, repeated, tag="1")]
    pub users: ::prost::alloc::vec::Vec<DeploymentUser>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeploymentRole {
    #[prost(string, tag="1")]
    pub role: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub db: ::prost::alloc::string::String,
    #[prost(bool, tag="3")]
    pub is_builtin: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListDeploymentRolesRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub database: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListDeploymentRolesResponse {
    #[prost(message, repeated, tag="1")]
    pub roles: ::prost::alloc::vec::Vec<DeploymentRole>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateDeploymentUserRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub database: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub password: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="5")]
    pub roles: ::prost::alloc::vec::Vec<RoleSpec>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateDeploymentUserRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub database: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub username: ::prost::alloc::string::String,
    /// unset or empty leaves the password unchanged
    #[prost(string, optional, tag="4")]
    pub password: ::core::option::Option<::prost::alloc::string::String>,
    /// repeated fields cannot distinguish "leave roles alone" from "remove all
    /// roles", so replace_roles says which: true replaces them with roles, even
    /// when roles is empty.
    #[prost(bool, tag="5")]
    pub replace_roles: bool,
    #[prost(message, repeated, tag="6")]
    pub roles: ::prost::alloc::vec::Vec<RoleSpec>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DropDeploymentUserRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub database: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub username: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExportRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub database: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub collection: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub filter_json: ::prost::alloc::string::String,
    /// "jsonl" | "csv"
    #[prost(string, tag="5")]
    pub format: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExportChunk {
    #[prost(bytes="bytes", tag="1")]
    pub data: ::prost::bytes::Bytes,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteFileRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub database: ::prost::alloc::string::String,
    /// empty => "fs"
    #[prost(string, tag="3")]
    pub bucket: ::prost::alloc::string::String,
    /// {"_id": <id>} in Extended JSON, as UploadFile returns; a ListFiles document also works
    #[prost(string, tag="4")]
    pub file_id_ejson: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteFileResponse {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListFilesRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub database: ::prost::alloc::string::String,
    /// empty => "fs"
    #[prost(string, tag="3")]
    pub bucket: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListFilesResponse {
    /// canonical Extended JSON file documents
    #[prost(string, repeated, tag="1")]
    pub files_ejson: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DownloadFileRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub database: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub bucket: ::prost::alloc::string::String,
    /// Extended JSON of the file _id value
    #[prost(string, tag="4")]
    pub file_id_ejson: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FileChunk {
    #[prost(bytes="bytes", tag="1")]
    pub data: ::prost::bytes::Bytes,
}
/// The first UploadChunk carries the metadata (+ optional first bytes);
/// subsequent messages carry only data.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UploadChunk {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub database: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub bucket: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub filename: ::prost::alloc::string::String,
    #[prost(bytes="bytes", tag="5")]
    pub data: ::prost::bytes::Bytes,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UploadFileResponse {
    #[prost(string, tag="1")]
    pub file_id_ejson: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MetadataAck {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListDatabasesRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListDatabasesResponse {
    #[prost(string, repeated, tag="1")]
    pub databases: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListCollectionsRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub database: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CollectionInfo {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    /// "collection" | "view" | "timeseries"
    #[prost(string, tag="2")]
    pub r#type: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListCollectionsResponse {
    #[prost(message, repeated, tag="1")]
    pub collections: ::prost::alloc::vec::Vec<CollectionInfo>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MongoVersionRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MongoVersionResponse {
    #[prost(string, tag="1")]
    pub version: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IndexInfo {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    /// canonical Extended JSON of the key pattern
    #[prost(string, tag="2")]
    pub keys_json: ::prost::alloc::string::String,
    #[prost(bool, tag="3")]
    pub unique: bool,
    #[prost(bool, tag="4")]
    pub sparse: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListIndexesRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub database: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub collection: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListIndexesResponse {
    #[prost(message, repeated, tag="1")]
    pub indexes: ::prost::alloc::vec::Vec<IndexInfo>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateIndexRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub database: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub collection: ::prost::alloc::string::String,
    /// e.g. {"email":1}
    #[prost(string, tag="4")]
    pub keys_json: ::prost::alloc::string::String,
    #[prost(bool, tag="5")]
    pub unique: bool,
    #[prost(bool, tag="6")]
    pub sparse: bool,
    /// optional
    #[prost(string, tag="7")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DropIndexRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub database: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub collection: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MonitoringAck {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ServerStatusRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ServerConnections {
    #[prost(int64, tag="1")]
    pub current: i64,
    #[prost(int64, tag="2")]
    pub available: i64,
    #[prost(int64, tag="3")]
    pub total_created: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OpCounters {
    #[prost(int64, tag="1")]
    pub insert: i64,
    #[prost(int64, tag="2")]
    pub query: i64,
    #[prost(int64, tag="3")]
    pub update: i64,
    #[prost(int64, tag="4")]
    pub delete: i64,
    #[prost(int64, tag="5")]
    pub getmore: i64,
    #[prost(int64, tag="6")]
    pub command: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ServerMemory {
    #[prost(int64, tag="1")]
    pub resident_mb: i64,
    #[prost(int64, tag="2")]
    pub virtual_mb: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ServerNetwork {
    #[prost(int64, tag="1")]
    pub bytes_in: i64,
    #[prost(int64, tag="2")]
    pub bytes_out: i64,
    #[prost(int64, tag="3")]
    pub num_requests: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CacheStats {
    #[prost(int64, tag="1")]
    pub bytes_in_cache: i64,
    #[prost(int64, tag="2")]
    pub max_bytes: i64,
    #[prost(int64, tag="3")]
    pub dirty_bytes: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerStatusResponse {
    #[prost(string, tag="1")]
    pub host: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub version: ::prost::alloc::string::String,
    #[prost(double, tag="3")]
    pub uptime_seconds: f64,
    #[prost(message, optional, tag="4")]
    pub connections: ::core::option::Option<ServerConnections>,
    #[prost(message, optional, tag="5")]
    pub opcounters: ::core::option::Option<OpCounters>,
    #[prost(message, optional, tag="6")]
    pub memory: ::core::option::Option<ServerMemory>,
    #[prost(message, optional, tag="7")]
    pub network: ::core::option::Option<ServerNetwork>,
    /// unset when the server reports no WiredTiger cache (e.g. mongos)
    #[prost(message, optional, tag="8")]
    pub cache: ::core::option::Option<CacheStats>,
    /// unset when the node is not a replica set member
    #[prost(string, optional, tag="9")]
    pub repl_set: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CurrentOpsRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CurrentOp {
    /// A string because mongos reports "shard:opid"; pass it back unchanged to KillOp.
    #[prost(string, tag="1")]
    pub opid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub op: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub ns: ::prost::alloc::string::String,
    #[prost(int64, tag="4")]
    pub secs_running: i64,
    #[prost(string, tag="5")]
    pub client: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub desc: ::prost::alloc::string::String,
    /// relaxed Extended JSON, truncated to 2000 characters
    #[prost(string, tag="7")]
    pub command: ::prost::alloc::string::String,
}
/// Active operations, longest-running first, capped at 200. Idle entries are omitted.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CurrentOpsResponse {
    #[prost(message, repeated, tag="1")]
    pub ops: ::prost::alloc::vec::Vec<CurrentOp>,
    /// more active operations existed than were returned
    #[prost(bool, tag="2")]
    pub truncated: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReplSetStatusRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReplSetMember {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub state_str: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub health: i64,
    #[prost(bool, tag="4")]
    pub self_: bool,
    #[prost(int64, tag="5")]
    pub uptime_secs: i64,
    #[prost(int64, tag="6")]
    pub optime_date_ms: i64,
    #[prost(int64, optional, tag="7")]
    pub ping_ms: ::core::option::Option<i64>,
    #[prost(string, tag="8")]
    pub sync_source: ::prost::alloc::string::String,
    /// unset for the primary, unhealthy members, or with no primary
    #[prost(double, optional, tag="9")]
    pub lag_secs: ::core::option::Option<f64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReplSetStatusResponse {
    #[prost(bool, tag="1")]
    pub is_replica_set: bool,
    /// "standalone" | "replicaSet" | "sharded"
    #[prost(string, tag="2")]
    pub cluster_type: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub set: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub my_state_str: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub mongo_version: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="6")]
    pub members: ::prost::alloc::vec::Vec<ReplSetMember>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct KillOpRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    /// as returned in CurrentOp.opid
    #[prost(string, tag="2")]
    pub opid: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetProfilingStatusRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub database: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SetProfilingLevelRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub database: ::prost::alloc::string::String,
    /// 0 off, 1 slow operations, 2 all operations
    #[prost(int32, tag="3")]
    pub level: i32,
    #[prost(int32, tag="4")]
    pub slow_ms: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProfilingStatus {
    #[prost(int64, tag="1")]
    pub level: i64,
    #[prost(int64, tag="2")]
    pub slow_ms: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReadProfileRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub database: ::prost::alloc::string::String,
    /// 0 means 50; clamped to 500
    #[prost(int64, tag="3")]
    pub limit: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProfileEntry {
    #[prost(string, tag="1")]
    pub op: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub ns: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub millis: i64,
    #[prost(int64, tag="4")]
    pub ts_ms: i64,
    #[prost(string, tag="5")]
    pub plan_summary: ::prost::alloc::string::String,
    /// relaxed Extended JSON, truncated to 2000 characters
    #[prost(string, tag="6")]
    pub command: ::prost::alloc::string::String,
}
/// Newest first.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReadProfileResponse {
    #[prost(message, repeated, tag="1")]
    pub entries: ::prost::alloc::vec::Vec<ProfileEntry>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AnalyzeSchemaRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub database: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub collection: ::prost::alloc::string::String,
    #[prost(int64, tag="4")]
    pub sample_size: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AnalyzeSchemaResponse {
    #[prost(int64, tag="1")]
    pub sampled: i64,
    #[prost(message, repeated, tag="2")]
    pub fields: ::prost::alloc::vec::Vec<FieldSchema>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TypeCount {
    #[prost(string, tag="1")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(int64, tag="2")]
    pub count: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldSchema {
    #[prost(string, tag="1")]
    pub path: ::prost::alloc::string::String,
    /// per-type occurrence counts
    #[prost(message, repeated, tag="2")]
    pub types: ::prost::alloc::vec::Vec<TypeCount>,
    /// documents containing this path
    #[prost(int64, tag="3")]
    pub presence: i64,
    /// presence / sampled
    #[prost(double, tag="4")]
    pub coverage: f64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MongoshClientMsg {
    /// set on the first message
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(bytes="bytes", tag="2")]
    pub input: ::prost::bytes::Bytes,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MongoshServerMsg {
    #[prost(bytes="bytes", tag="1")]
    pub output: ::prost::bytes::Bytes,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DbStatsRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub database: ::prost::alloc::string::String,
}
/// Missing or non-numeric server fields read as 0.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DbStatsResponse {
    #[prost(int64, tag="1")]
    pub collections: i64,
    #[prost(int64, tag="2")]
    pub views: i64,
    #[prost(int64, tag="3")]
    pub objects: i64,
    #[prost(double, tag="4")]
    pub avg_obj_size: f64,
    #[prost(int64, tag="5")]
    pub data_size: i64,
    #[prost(int64, tag="6")]
    pub storage_size: i64,
    #[prost(int64, tag="7")]
    pub indexes: i64,
    #[prost(int64, tag="8")]
    pub total_index_size: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CollStatsRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub database: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub collection: ::prost::alloc::string::String,
}
/// On a sharded collection the counts and sizes are summed across shards.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CollStatsResponse {
    #[prost(int64, tag="1")]
    pub count: i64,
    #[prost(double, tag="2")]
    pub avg_obj_size: f64,
    #[prost(int64, tag="3")]
    pub size: i64,
    #[prost(int64, tag="4")]
    pub storage_size: i64,
    #[prost(int64, tag="5")]
    pub nindexes: i64,
    #[prost(int64, tag="6")]
    pub total_index_size: i64,
    #[prost(bool, tag="7")]
    pub capped: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IndexStatsRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub database: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub collection: ::prost::alloc::string::String,
}
/// ops and since_ms are 0 when usage stats are unavailable (views, old servers).
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IndexStat {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    #[prost(int64, tag="2")]
    pub size_bytes: i64,
    #[prost(int64, tag="3")]
    pub ops: i64,
    /// epoch milliseconds usage counting started
    #[prost(int64, tag="4")]
    pub since_ms: i64,
}
/// Sorted by size_bytes, largest first.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IndexStatsResponse {
    #[prost(message, repeated, tag="1")]
    pub indexes: ::prost::alloc::vec::Vec<IndexStat>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WriteResult {
    #[prost(int64, tag="1")]
    pub matched_count: i64,
    #[prost(int64, tag="2")]
    pub modified_count: i64,
    #[prost(int64, tag="3")]
    pub deleted_count: i64,
    #[prost(string, tag="4")]
    pub upserted_id_json: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InsertDocumentRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub database: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub collection: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub document_json: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InsertDocumentResponse {
    #[prost(string, tag="1")]
    pub inserted_id_json: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateDocumentRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub database: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub collection: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub filter_json: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub update_json: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReplaceDocumentRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub database: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub collection: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub filter_json: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub replacement_json: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteDocumentRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub database: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub collection: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub filter_json: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateManyRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub database: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub collection: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub filter_json: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub update_json: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteManyRequest {
    #[prost(string, tag="1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub database: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub collection: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub filter_json: ::prost::alloc::string::String,
}
include!("mqlens.v1.tonic.rs");
// @@protoc_insertion_point(module)